# Generated by Django 5.1.3 on 2024-11-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('brand_price', models.IntegerField()),
                ('brand_category', models.CharField(max_length=50)),
                ('brand_qty', models.IntegerField()),
                ('brand_img', models.ImageField(upload_to='brands/')),
                ('brand_desc', models.TextField()),
            ],
        ),
    ]
